"""Coverage gap tests identified by audit.

Four distinct gaps are covered here:

Gap 1: Full-tree export/import round-trip with ALL model types populated.
Gap 2: Multi-level orphan cascade — 4 levels deep, falsification propagates
        only one level (direct dependents), not transitively.
Gap 3: Invalid arc integer passed to cb_manage_assertion returns ERROR.
Gap 4: Promote to same or weaker arc raises ValueError.
"""

import pytest

from cognitive_bridge.models import (
    Assertion,
    AssertionAuthor,
    AssumptionStatus,
    CompositionArc,
    CompositionStage,
    ConflictStatus,
    Decision,
    EventType,
)
from cognitive_bridge.models.arcs import ConflictDetectionLayer, ResolutionPath, _new_id
from cognitive_bridge.models.conflict import Conflict
from cognitive_bridge.models.variant_set import Variant, VariantSet
from cognitive_bridge.engine.resolver import (
    add_assertion,
    falsify_assertion,
    promote_assertion,
    retract_assertion,
)
from cognitive_bridge.server import export_stage_to_json, import_stage_from_json
from cognitive_bridge.storage.sqlite_store import SQLiteStore


# ═══════════════════════════════════════════════════════════════════════════
# Shared mock context (mirrors pattern from test_assertion_tool.py)
# ═══════════════════════════════════════════════════════════════════════════


class _MockCtx:
    """Minimal context mock that satisfies ctx.lifespan_context access."""

    def __init__(self, store: SQLiteStore, stage: CompositionStage) -> None:
        self.lifespan_context = {
            "store": store,
            "active_stages": {stage.project_id: stage},
        }


def _make_ctx_with_stage(
    project_id: str = "gap_test",
) -> tuple["_MockCtx", CompositionStage, SQLiteStore]:
    """Build a wired (ctx, stage, store) triple for tool-level tests."""
    from cognitive_bridge.server import save_stage_to_db

    store = SQLiteStore(":memory:")
    stage = CompositionStage(project_id=project_id, project_name="Gap Test")
    save_stage_to_db(store, stage)
    ctx = _MockCtx(store=store, stage=stage)
    return ctx, stage, store


# ═══════════════════════════════════════════════════════════════════════════
# Gap 1 — Full-tree export/import round-trip with ALL model types
# ═══════════════════════════════════════════════════════════════════════════


def _build_full_stage() -> CompositionStage:
    """Build a maximally populated stage covering every model type."""
    stage = CompositionStage(
        project_id="rt_full_001",
        project_name="Full Round-Trip",
    )
    stage.exchange_count = 42

    # --- Custom CognitiveParameters (not defaults) ---
    stage.parameters.conflict_sensitivity = 0.91
    stage.parameters.semantic_threshold = 0.88
    stage.parameters.cross_path_detection = True
    stage.parameters.exploration_budget = 7
    stage.parameters.red_team_threshold = 15
    stage.parameters.cascade_auto_challenge = False
    stage.parameters.payload_surfacing = False
    stage.parameters.ai_default_arc = CompositionArc.REFERENCES

    # --- Assertions at different paths with various arcs & dependencies ---
    # A: LOCAL at /db (root for DAG)
    ast_a = Assertion(
        topic_path="/db",
        content="PostgreSQL is the primary datastore",
        arc=CompositionArc.LOCAL,
        author=AssertionAuthor.AI,
        falsifiable_if="If another DB engine is chosen by the team",
    )
    stage.assertions[ast_a.id] = ast_a

    # B: INHERITS at /db/orm, depends on /db
    ast_b = Assertion(
        topic_path="/db/orm",
        content="Prisma is the ORM layer",
        arc=CompositionArc.INHERITS,
        author=AssertionAuthor.AI,
        depends_on_paths=["/db"],
    )
    stage.assertions[ast_b.id] = ast_b

    # C: REFERENCES at /db/hosting
    ast_c = Assertion(
        topic_path="/db/hosting",
        content="Database is hosted on AWS RDS",
        arc=CompositionArc.REFERENCES,
        author=AssertionAuthor.USER,
    )
    stage.assertions[ast_c.id] = ast_c

    # D: SPECIALIZES at /api/schema, depends on /db/orm
    ast_d = Assertion(
        topic_path="/api/schema",
        content="API schema is auto-generated by Prisma",
        arc=CompositionArc.SPECIALIZES,
        author=AssertionAuthor.AI,
        depends_on_paths=["/db/orm"],
    )
    stage.assertions[ast_d.id] = ast_d

    # E: PAYLOADS at /compliance
    ast_e = Assertion(
        topic_path="/compliance",
        content="GDPR compliance audit pending",
        arc=CompositionArc.PAYLOADS,
        author=AssertionAuthor.SYSTEM,
        depends_on_paths=["/db"],
    )
    stage.assertions[ast_e.id] = ast_e

    # --- Conflicts ---
    # Active conflict between ast_a and a hypothetical MongoDB claim
    cfl_active = Conflict(
        assertion_a_id=ast_a.id,
        assertion_b_id=ast_c.id,
        topic_path="/db",
        detection_layer=ConflictDetectionLayer.STRUCTURAL,
        steelman_of_opponent="MongoDB offers flexible schema — suits evolving requirements",
    )
    stage.conflicts[cfl_active.id] = cfl_active

    # Resolved conflict
    cfl_resolved = Conflict(
        assertion_a_id=ast_b.id,
        assertion_b_id=ast_d.id,
        topic_path="/db/orm",
        detection_layer=ConflictDetectionLayer.CASCADING,
        status=ConflictStatus.RESOLVED_SYNTHESIZED,
        resolution_chosen=ResolutionPath.SYNTHESIZE,
        resolution_note="Both claims are compatible; schema generation follows ORM.",
    )
    stage.conflicts[cfl_resolved.id] = cfl_resolved

    # --- VariantSet with 2 variants ---
    vs = VariantSet(
        name="Database Options",
        topic_path="/db",
        variants=[
            Variant(
                name="PostgreSQL",
                content="Relational; strong ACID guarantees",
                evidence_for=["joins", "ACID"],
            ),
            Variant(
                name="MongoDB",
                content="Document store; flexible schema",
                evidence_for=["flexible schema"],
                evidence_against=["no joins"],
            ),
        ],
        source_conflict_id=cfl_active.id,
    )
    stage.variant_sets[vs.id] = vs

    # --- Decisions ---
    dec_a = Decision(
        topic_path="/db",
        decision="Use PostgreSQL for the primary datastore",
        rationale="Team has SQL expertise and schema is well-defined",
        alternatives_rejected=[
            "MongoDB — rejected because no native join support",
            "MySQL — rejected because Prisma ORM support is weaker",
        ],
        second_order_effects=[
            "All queries must use SQL dialect",
            "Schema migrations required via Prisma migrate",
        ],
    )
    stage.decisions.append(dec_a)

    dec_b = Decision(
        topic_path="/api/schema",
        decision="Auto-generate API schema from Prisma models",
        rationale="Single source of truth reduces drift between DB and API",
        alternatives_rejected=["Hand-crafted OpenAPI — rejected because of maintenance burden"],
        second_order_effects=["Schema changes must go through Prisma first"],
    )
    stage.decisions.append(dec_b)

    # --- Events ---
    for evt_type in [
        EventType.ASSERTION_CREATED,
        EventType.ASSERTION_PROMOTED,
        EventType.CONFLICT_DETECTED,
        EventType.CONFLICT_RESOLVED,
        EventType.ASSERTION_CHALLENGED,
        EventType.ASSERTION_FALSIFIED,
        EventType.ASSERTION_ORPHANED,
        EventType.VARIANT_SET_CREATED,
        EventType.DECISION_RECORDED,
        EventType.PARAMETERS_TUNED,
    ]:
        stage.record_event(
            evt_type,
            AssertionAuthor.SYSTEM,
            "target_001",
            {"test_event": evt_type.value},
        )

    return stage


class TestFullRoundTrip:
    """Gap 1: export/import round-trip preserving all model types."""

    def test_assertion_count_survives_round_trip(self) -> None:
        """All 5 assertions survive the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))
        assert len(recovered.assertions) == len(original.assertions)

    def test_conflict_count_survives_round_trip(self) -> None:
        """Both conflicts (active and resolved) survive the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))
        assert len(recovered.conflicts) == len(original.conflicts)

    def test_variant_set_count_survives_round_trip(self) -> None:
        """The VariantSet survives the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))
        assert len(recovered.variant_sets) == len(original.variant_sets)

    def test_decision_count_survives_round_trip(self) -> None:
        """Both decisions survive the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))
        assert len(recovered.decisions) == len(original.decisions)

    def test_event_count_survives_round_trip(self) -> None:
        """All 10 events survive the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))
        assert len(recovered.events) == len(original.events)

    def test_local_assertion_falsifiable_if_survives(self) -> None:
        """LOCAL assertion's falsifiable_if field survives the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))

        # Find the LOCAL assertion at /db
        local_assertions = [
            a for a in recovered.assertions.values()
            if a.arc == CompositionArc.LOCAL and a.topic_path == "/db"
        ]
        assert len(local_assertions) == 1
        assert local_assertions[0].falsifiable_if == "If another DB engine is chosen by the team"

    def test_assertion_depends_on_paths_survives(self) -> None:
        """depends_on_paths DAG edges survive the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))

        # Find the ORM assertion at /db/orm
        orm_assertions = [
            a for a in recovered.assertions.values()
            if a.topic_path == "/db/orm"
        ]
        assert len(orm_assertions) == 1
        assert "/db" in orm_assertions[0].depends_on_paths

    def test_assertion_arc_survives(self) -> None:
        """Arc values survive the round-trip correctly."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))

        arcs_original = {a.arc for a in original.assertions.values()}
        arcs_recovered = {a.arc for a in recovered.assertions.values()}
        assert arcs_original == arcs_recovered

    def test_active_conflict_status_survives(self) -> None:
        """Active conflict status survives the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))

        active = [c for c in recovered.conflicts.values() if c.status == ConflictStatus.ACTIVE]
        assert len(active) == 1

    def test_resolved_conflict_status_survives(self) -> None:
        """Resolved conflict status and resolution_chosen survive."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))

        resolved = [
            c for c in recovered.conflicts.values()
            if c.status == ConflictStatus.RESOLVED_SYNTHESIZED
        ]
        assert len(resolved) == 1
        assert resolved[0].resolution_chosen == ResolutionPath.SYNTHESIZE

    def test_conflict_steelman_survives(self) -> None:
        """steelman_of_opponent survives the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))

        active = [c for c in recovered.conflicts.values() if c.status == ConflictStatus.ACTIVE]
        assert len(active) == 1
        assert "MongoDB" in active[0].steelman_of_opponent

    def test_conflict_detection_layer_survives(self) -> None:
        """detection_layer on each conflict survives the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))

        layers_original = {c.detection_layer for c in original.conflicts.values()}
        layers_recovered = {c.detection_layer for c in recovered.conflicts.values()}
        assert layers_original == layers_recovered

    def test_decision_alternatives_rejected_survives(self) -> None:
        """alternatives_rejected on decisions survive the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))

        db_dec = next(
            d for d in recovered.decisions if d.topic_path == "/db"
        )
        assert len(db_dec.alternatives_rejected) == 2
        assert any("MongoDB" in alt for alt in db_dec.alternatives_rejected)

    def test_decision_second_order_effects_survives(self) -> None:
        """second_order_effects on decisions survive the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))

        db_dec = next(
            d for d in recovered.decisions if d.topic_path == "/db"
        )
        assert len(db_dec.second_order_effects) == 2

    def test_parameters_all_eight_fields_survive(self) -> None:
        """All 8 CognitiveParameters fields survive the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))

        p = recovered.parameters
        assert p.conflict_sensitivity == pytest.approx(0.91)
        assert p.semantic_threshold == pytest.approx(0.88)
        assert p.cross_path_detection is True
        assert p.exploration_budget == 7
        assert p.red_team_threshold == 15
        assert p.cascade_auto_challenge is False
        assert p.payload_surfacing is False
        assert p.ai_default_arc == CompositionArc.REFERENCES

    def test_exchange_count_survives(self) -> None:
        """exchange_count survives the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))
        assert recovered.exchange_count == 42

    def test_variant_set_variants_survive(self) -> None:
        """Both variants inside the VariantSet survive the round-trip."""
        original = _build_full_stage()
        recovered = import_stage_from_json(export_stage_to_json(original))

        vs_list = list(recovered.variant_sets.values())
        assert len(vs_list) == 1
        vs = vs_list[0]
        assert len(vs.variants) == 2
        names = {v.name for v in vs.variants}
        assert names == {"PostgreSQL", "MongoDB"}

    def test_embeddings_preserved_via_explicit_inclusion(self) -> None:
        """export_stage_to_json re-injects embedding after model_dump(exclude=True).

        The export code does: {**v.model_dump(mode="json"), "embedding": v.embedding}
        which explicitly adds the embedding back even though the field has exclude=True
        in the Pydantic schema. This means embeddings DO survive the round-trip when
        set in-memory before export.
        """
        original = _build_full_stage()
        # Manually set an embedding on one assertion
        ast = next(iter(original.assertions.values()))
        ast.embedding = [0.1, 0.2, 0.3]

        recovered = import_stage_from_json(export_stage_to_json(original))
        recovered_ast = recovered.assertions[ast.id]
        # The export explicitly re-includes embeddings, so they survive
        assert recovered_ast.embedding == [0.1, 0.2, 0.3]

    def test_assertion_with_no_embedding_imports_as_none(self) -> None:
        """Assertions without an embedding have embedding=None after round-trip."""
        original = _build_full_stage()
        # Verify none of the assertions have embeddings set in _build_full_stage
        for ast in original.assertions.values():
            assert ast.embedding is None

        recovered = import_stage_from_json(export_stage_to_json(original))
        for ast in recovered.assertions.values():
            assert ast.embedding is None


# ═══════════════════════════════════════════════════════════════════════════
# Gap 2 — Multi-level orphan cascade (4 levels deep)
# ═══════════════════════════════════════════════════════════════════════════


class TestMultiLevelOrphanCascade:
    """Gap 2: falsify_assertion only ORPHANs direct dependents (one level).

    The DAG:
        A @ /level/one (LOCAL, falsifiable)
        B @ /level/two  depends_on: [/level/one]
        C @ /level/three depends_on: [/level/two]
        D @ /level/four  depends_on: [/level/three]

    Falsifying A marks A FALSIFIED and B ORPHANED (direct), but C and D
    are not directly affected by the falsification call — they depend on
    /level/two and /level/three respectively, not on /level/one.
    """

    def _build_chain_stage(self) -> tuple[CompositionStage, str, str, str, str]:
        """Build a 4-level dependency chain and return (stage, id_a, id_b, id_c, id_d)."""
        stage = CompositionStage(project_id="orphan_chain", project_name="Orphan Chain")

        ast_a = Assertion(
            topic_path="/level/one",
            content="Foundation claim at level one",
            arc=CompositionArc.LOCAL,
            author=AssertionAuthor.AI,
            falsifiable_if="If level-one assumption is disproven by experiment",
        )
        stage.assertions[ast_a.id] = ast_a

        ast_b = Assertion(
            topic_path="/level/two",
            content="Derived claim at level two",
            arc=CompositionArc.INHERITS,
            author=AssertionAuthor.AI,
            depends_on_paths=["/level/one"],
        )
        stage.assertions[ast_b.id] = ast_b

        ast_c = Assertion(
            topic_path="/level/three",
            content="Derived claim at level three",
            arc=CompositionArc.INHERITS,
            author=AssertionAuthor.AI,
            depends_on_paths=["/level/two"],
        )
        stage.assertions[ast_c.id] = ast_c

        ast_d = Assertion(
            topic_path="/level/four",
            content="Derived claim at level four",
            arc=CompositionArc.SPECIALIZES,
            author=AssertionAuthor.AI,
            depends_on_paths=["/level/three"],
        )
        stage.assertions[ast_d.id] = ast_d

        return stage, ast_a.id, ast_b.id, ast_c.id, ast_d.id

    def test_falsified_assertion_is_marked_falsified(self) -> None:
        """After falsify_assertion(A), A's assumption_status is FALSIFIED."""
        stage, id_a, id_b, id_c, id_d = self._build_chain_stage()
        falsify_assertion(stage, id_a, "Experiment showed level-one is wrong")
        assert stage.assertions[id_a].assumption_status == AssumptionStatus.FALSIFIED

    def test_direct_dependent_is_orphaned(self) -> None:
        """B, which directly depends on /level/one, becomes ORPHANED."""
        stage, id_a, id_b, id_c, id_d = self._build_chain_stage()
        falsify_assertion(stage, id_a, "Experiment showed level-one is wrong")
        assert stage.assertions[id_b].assumption_status == AssumptionStatus.ORPHANED

    def test_indirect_dependent_stays_live(self) -> None:
        """C depends on /level/two (not /level/one directly) — stays LIVE after falsifying A."""
        stage, id_a, id_b, id_c, id_d = self._build_chain_stage()
        falsify_assertion(stage, id_a, "Experiment showed level-one is wrong")
        # C's dependency path is /level/two, not /level/one. check_falsification
        # only orphans direct dependents of the falsified path.
        assert stage.assertions[id_c].assumption_status == AssumptionStatus.LIVE

    def test_level_four_stays_live(self) -> None:
        """D depends only on /level/three — stays LIVE after falsifying A."""
        stage, id_a, id_b, id_c, id_d = self._build_chain_stage()
        falsify_assertion(stage, id_a, "Experiment showed level-one is wrong")
        assert stage.assertions[id_d].assumption_status == AssumptionStatus.LIVE

    def test_falsified_assertion_is_deactivated(self) -> None:
        """Falsified assertion has active=False after falsify_assertion."""
        stage, id_a, id_b, id_c, id_d = self._build_chain_stage()
        falsify_assertion(stage, id_a, "Experiment showed level-one is wrong")
        assert stage.assertions[id_a].active is False

    def test_orphaned_dependent_stays_active(self) -> None:
        """B is ORPHANED but still active (not retracted — different lifecycle)."""
        stage, id_a, id_b, id_c, id_d = self._build_chain_stage()
        falsify_assertion(stage, id_a, "Experiment showed level-one is wrong")
        # ORPHANED changes assumption_status but does not set active=False
        assert stage.assertions[id_b].active is True

    def test_retract_b_then_c_becomes_orphaned(self) -> None:
        """If B is then retracted, C (depending on /level/two) becomes ORPHANED."""
        stage, id_a, id_b, id_c, id_d = self._build_chain_stage()
        falsify_assertion(stage, id_a, "Experiment showed level-one is wrong")
        # B is now orphaned; retract it to propagate to C
        retract_assertion(stage, id_b)
        assert stage.assertions[id_c].assumption_status == AssumptionStatus.ORPHANED

    def test_events_recorded_for_falsification(self) -> None:
        """ASSERTION_FALSIFIED and ASSERTION_ORPHANED events are recorded."""
        stage, id_a, id_b, id_c, id_d = self._build_chain_stage()
        falsify_assertion(stage, id_a, "Experiment showed level-one is wrong")

        event_types = {e.event_type for e in stage.events}
        assert EventType.ASSERTION_FALSIFIED in event_types
        assert EventType.ASSERTION_ORPHANED in event_types

    def test_only_one_orphan_event_recorded_for_single_dependent(self) -> None:
        """Exactly one ASSERTION_ORPHANED event is recorded (only B is direct dependent)."""
        stage, id_a, id_b, id_c, id_d = self._build_chain_stage()
        falsify_assertion(stage, id_a, "Experiment showed level-one is wrong")

        orphan_events = [
            e for e in stage.events
            if e.event_type == EventType.ASSERTION_ORPHANED
        ]
        assert len(orphan_events) == 1
        assert orphan_events[0].target_id == id_b


# ═══════════════════════════════════════════════════════════════════════════
# Gap 3 — Invalid arc integer passed to cb_manage_assertion
# ═══════════════════════════════════════════════════════════════════════════


class TestInvalidArcValue:
    """Gap 3: cb_manage_assertion behaviour for invalid arc integer values.

    The assertion tool calls ``CompositionArc(arc)`` at line 255 of assertion_tool.py
    BEFORE the try/except block that wraps Assertion construction. This means an
    invalid arc integer raises a raw ValueError instead of being caught and returned
    as an ERROR string. The tests below document the actual behaviour of the code.

    Note: this is a documentation/characterisation test suite. The tests confirm
    what the code does so that any future fix to return an ERROR string instead will
    cause these tests to fail and prompt an intentional update.
    """

    @pytest.mark.asyncio
    async def test_arc_999_raises_value_error(self) -> None:
        """arc=999 is not a valid CompositionArc — returns ERROR string."""
        from cognitive_bridge.tools.assertion_tool import cb_manage_assertion

        ctx, stage, store = _make_ctx_with_stage("gap3_arc999")
        result = await cb_manage_assertion(
            action="assert",
            topic_path="/test/path",
            content="some claim",
            arc=999,
            ctx=ctx,
            project_id="gap3_arc999",
        )
        assert "ERROR" in result
        assert "Invalid arc" in result or "999" in result

    @pytest.mark.asyncio
    async def test_arc_15_returns_error(self) -> None:
        """arc=15 falls between valid values — returns ERROR string."""
        from cognitive_bridge.tools.assertion_tool import cb_manage_assertion

        ctx, stage, store = _make_ctx_with_stage("gap3_arc15")
        result = await cb_manage_assertion(
            action="assert",
            topic_path="/test/path",
            content="some claim",
            arc=15,
            ctx=ctx,
            project_id="gap3_arc15",
        )
        assert "ERROR" in result

    @pytest.mark.asyncio
    async def test_arc_negative_returns_error(self) -> None:
        """arc=-1 is not a valid CompositionArc value — returns ERROR string."""
        from cognitive_bridge.tools.assertion_tool import cb_manage_assertion

        ctx, stage, store = _make_ctx_with_stage("gap3_neg")
        result = await cb_manage_assertion(
            action="assert",
            topic_path="/test/path",
            content="some claim",
            arc=-1,
            ctx=ctx,
            project_id="gap3_neg",
        )
        assert "ERROR" in result

    @pytest.mark.asyncio
    async def test_arc_zero_returns_error(self) -> None:
        """arc=0 is not a defined CompositionArc value — returns ERROR string."""
        from cognitive_bridge.tools.assertion_tool import cb_manage_assertion

        ctx, stage, store = _make_ctx_with_stage("gap3_zero")
        result = await cb_manage_assertion(
            action="assert",
            topic_path="/test/path",
            content="some claim",
            arc=0,
            ctx=ctx,
            project_id="gap3_zero",
        )
        assert "ERROR" in result

    @pytest.mark.asyncio
    async def test_valid_arc_does_not_raise(self) -> None:
        """Sanity-check: a valid arc (SPECIALIZES=60) succeeds without raising."""
        from cognitive_bridge.tools.assertion_tool import cb_manage_assertion

        ctx, stage, store = _make_ctx_with_stage("gap3_valid")
        result = await cb_manage_assertion(
            action="assert",
            topic_path="/test/path",
            content="some claim",
            arc=60,
            ctx=ctx,
            project_id="gap3_valid",
        )
        assert not result.startswith("ERROR")


# ═══════════════════════════════════════════════════════════════════════════
# Gap 4 — Promote to same or weaker arc
# ═══════════════════════════════════════════════════════════════════════════


class TestPromoteToSameOrWeakerArc:
    """Gap 4: promote_assertion raises ValueError when new arc is not stronger."""

    def _make_inherits_stage(self) -> tuple[CompositionStage, str]:
        """Create a stage with a single INHERITS assertion and return (stage, id)."""
        stage = CompositionStage(project_id="promote_test", project_name="Promote Test")
        ast = Assertion(
            topic_path="/test/promote",
            content="Claim to be promoted",
            arc=CompositionArc.INHERITS,
            author=AssertionAuthor.AI,
        )
        stage.assertions[ast.id] = ast
        return stage, ast.id

    def test_promote_to_same_arc_raises(self) -> None:
        """Promoting INHERITS -> INHERITS (same arc) raises ValueError."""
        stage, ast_id = self._make_inherits_stage()
        with pytest.raises(ValueError, match="not stronger"):
            promote_assertion(stage, ast_id, CompositionArc.INHERITS)

    def test_promote_to_weaker_arc_raises(self) -> None:
        """Promoting INHERITS(20) -> REFERENCES(40) is a demotion — raises ValueError."""
        stage, ast_id = self._make_inherits_stage()
        with pytest.raises(ValueError, match="not stronger"):
            promote_assertion(stage, ast_id, CompositionArc.REFERENCES)

    def test_promote_to_weakest_arc_raises(self) -> None:
        """Promoting INHERITS(20) -> SPECIALIZES(60) raises ValueError."""
        stage, ast_id = self._make_inherits_stage()
        with pytest.raises(ValueError, match="not stronger"):
            promote_assertion(stage, ast_id, CompositionArc.SPECIALIZES)

    def test_promote_to_payloads_from_inherits_raises(self) -> None:
        """Promoting INHERITS(20) -> PAYLOADS(50) raises ValueError."""
        stage, ast_id = self._make_inherits_stage()
        with pytest.raises(ValueError, match="not stronger"):
            promote_assertion(stage, ast_id, CompositionArc.PAYLOADS)

    def test_promote_to_stronger_arc_succeeds(self) -> None:
        """Promoting INHERITS(20) -> LOCAL(10) succeeds (legitimate promotion)."""
        stage, ast_id = self._make_inherits_stage()
        # LOCAL requires falsifiable_if — we must supply it via the assertion update.
        # promote_assertion mutates the arc; we need a LOCAL-safe arc.
        # Use LOCAL which is stronger (10 < 20).
        # But LOCAL assertions need falsifiable_if — add it before promoting.
        stage.assertions[ast_id].falsifiable_if = "If the claim fails a test"
        result = promote_assertion(stage, ast_id, CompositionArc.LOCAL)
        assert result.assertion.arc == CompositionArc.LOCAL

    def test_promote_nonexistent_assertion_raises(self) -> None:
        """Promoting an ID that does not exist raises ValueError."""
        stage, _ = self._make_inherits_stage()
        with pytest.raises(ValueError, match="not found"):
            promote_assertion(stage, "ast_nonexistent", CompositionArc.LOCAL)

    def test_promote_retracted_assertion_raises(self) -> None:
        """Promoting a retracted (inactive) assertion raises ValueError."""
        stage, ast_id = self._make_inherits_stage()
        # Retract it first
        retract_assertion(stage, ast_id)
        with pytest.raises(ValueError, match="inactive"):
            promote_assertion(stage, ast_id, CompositionArc.LOCAL)

    def test_promote_error_message_names_arcs(self) -> None:
        """ValueError message names both old and new arc for diagnostics."""
        stage, ast_id = self._make_inherits_stage()
        with pytest.raises(ValueError) as exc_info:
            promote_assertion(stage, ast_id, CompositionArc.REFERENCES)
        msg = str(exc_info.value)
        # Message should reference the arc names or values
        assert "REFERENCES" in msg or "40" in msg
        assert "INHERITS" in msg or "20" in msg
